//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodation
    {
        public int fID { get; set; }
        public Nullable<int> eID { get; set; }
        public string Name { get; set; }
        public string addr { get; set; }
        public Nullable<int> aroom { get; set; }
        public Nullable<int> bud { get; set; }
        public string CNo { get; set; }
        public string avfrom { get; set; }
        public string fcatgory { get; set; }
    }
}
