//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableRoute
    {
        public int ID { get; set; }
        public Nullable<int> EID { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public string Des { get; set; }
        public Nullable<int> Seat { get; set; }
        public string CNo { get; set; }
        public string rdetail { get; set; }
    }
}
